
services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: maintenance-postgres
    restart: no
    environment:
      POSTGRES_DB: maintenance_dev
      POSTGRES_USER: maintenance_user
      POSTGRES_PASSWORD: 12345
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_maintenance:/var/lib/postgresql/data


volumes:
  postgres_data_maintenance:

